### ISSUE TITLE
EZWBC 1.6 dont relay rangefinder and distance sensor message to mission planner

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#123] opened 2018-05-25 08:54 UTC

**Comment by rodizio1** [comment] 2018-05-28 17:16
Probably also caused by incompatibility of the mavlink.org Mavlink libs I use and different ArduCopter libs. Will be fixed as soon as I've written a Mavlink parser that doesn't suffer from these incompatibilities.

**Comment by roque-canales** [comment] 2018-09-06 15:00
Hello Rodizio, What's up ?

**Comment by bortek** [comment] 2018-11-02 10:14
I am trying to clean up the clutter @Yes21 , do you know if this is still relevant or can we close it ?

**Comment by Yes21** [comment] 2018-11-02 14:40
Mavlink2 implementation will solve it.

**Closed by Yes21** 2018-11-02 14:40 UTC
